# Generated by Django 2.1.5 on 2020-02-19 11:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0002_favoriterestaurant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoriteRestaurant',
            new_name='FavoriteItem',
        ),
    ]
